### ISSUE TITLE
Low quality listings

### ISSUE THREAD

**Issue by mcintyre321** [api-commons/api-commons#4]
Hi,

I've been doing some very initial work on a similar concept at http://apinest.com and would be happy to rip out my API registry code if api-commons were to cover my uses cases.

One of the (work-in-progress) features of apinest.com is that you can mash apis together with middleware proxies to create new apis, so apis can be created very quickly, and with relatively low quality and/or guarantees of service. 

I'd like to auto-register the mashups into the directory automatically, but it looks like this would pollute your listings as there's no rating/popularity system. Is the 'low quality listing' a use case you would support? IMO it's important if you want a vibrant, app-store-like experience.

**Comment by kinlane** [comment]
Hey there...thanks for interest. I get what you are trying to do. I'd recommend looking at http://apis.io, http://theapistack.com, and https://apis.guru/ to get what you need. API Commons is meant to be more of a legal specification / designation for each API rather than a directory....we just happen to have a directory of APIs who have applied. Let me know if you need help navigating the specifications available at these there locations.
